---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bbck-dev
spec:
  secretName: bbck-dev-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "bbck.dev"
  dnsNames:
    - "bbck.dev"
    - "*.bbck.dev"
