---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./csi-driver-nfs.yaml
  - ./grafana.yaml
  - ./longhorn.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
